"""add magazine articles and tags

Revision ID: 042c9aaf2b74
Revises: c326aa6733b5
Create Date: 2026-10-08 18:12:07.942003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042c9aaf2b74'
down_revision: Union[str, Sequence[str], None] = 'c326aa6733b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magazine_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('standfirst', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magazine_articles_author_name'), 'magazine_articles', ['author_name'], unique=False)
    op.create_index(op.f('ix_magazine_articles_category'), 'magazine_articles', ['category'], unique=False)
    op.create_index(op.f('ix_magazine_articles_country_code'), 'magazine_articles', ['country_code'], unique=False)
    op.create_index(op.f('ix_magazine_articles_published_at'), 'magazine_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_magazine_articles_slug'), 'magazine_articles', ['slug'], unique=True)
    op.create_index(op.f('ix_magazine_articles_status'), 'magazine_articles', ['status'], unique=False)
    op.create_table('magazine_article_tags',
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['magazine_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('magazine_article_tags')
    op.drop_index(op.f('ix_magazine_articles_status'), table_name='magazine_articles')
    op.drop_index(op.f('ix_magazine_articles_slug'), table_name='magazine_articles')
    op.drop_index(op.f('ix_magazine_articles_published_at'), table_name='magazine_articles')
    op.drop_index(op.f('ix_magazine_articles_country_code'), table_name='magazine_articles')
    op.drop_index(op.f('ix_magazine_articles_category'), table_name='magazine_articles')
    op.drop_index(op.f('ix_magazine_articles_author_name'), table_name='magazine_articles')
    op.drop_table('magazine_articles')
    # ### end Alembic commands ###
