"""add content_type and video_url to magazine articles

Revision ID: 108af4f4322a
Revises: 35b4b9d76129
Create Date: 2026-10-10 10:48:02.048096

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108af4f4322a'
down_revision: Union[str, Sequence[str], None] = '35b4b9d76129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Expand: existing rows backfill to "article" so the NOT NULL holds on a
    # database that already has magazine content (Render runs this before code).
    op.add_column(
        'magazine_articles',
        sa.Column('content_type', sa.String(length=20), nullable=False, server_default='article'),
    )
    op.add_column('magazine_articles', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_magazine_articles_content_type'), 'magazine_articles', ['content_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_magazine_articles_content_type'), table_name='magazine_articles')
    op.drop_column('magazine_articles', 'video_url')
    op.drop_column('magazine_articles', 'content_type')
    # ### end Alembic commands ###
