"""add cpd training catalog tables

Revision ID: 35b4b9d76129
Revises: 042c9aaf2b74
Create Date: 2026-10-08 19:41:23.821245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b4b9d76129'
down_revision: Union[str, Sequence[str], None] = '042c9aaf2b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_providers_country_code'), 'training_providers', ['country_code'], unique=False)
    op.create_index(op.f('ix_training_providers_name'), 'training_providers', ['name'], unique=False)
    op.create_table('training_courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('subdivision_code', sa.String(length=30), nullable=False),
    sa.Column('delivery_mode', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['training_providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_courses_country_code'), 'training_courses', ['country_code'], unique=False)
    op.create_index(op.f('ix_training_courses_delivery_mode'), 'training_courses', ['delivery_mode'], unique=False)
    op.create_index(op.f('ix_training_courses_provider_id'), 'training_courses', ['provider_id'], unique=False)
    op.create_index(op.f('ix_training_courses_subdivision_code'), 'training_courses', ['subdivision_code'], unique=False)
    op.create_index(op.f('ix_training_courses_title'), 'training_courses', ['title'], unique=False)
    op.create_table('training_webinars',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('join_url', sa.String(length=500), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['training_providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_webinars_country_code'), 'training_webinars', ['country_code'], unique=False)
    op.create_index(op.f('ix_training_webinars_provider_id'), 'training_webinars', ['provider_id'], unique=False)
    op.create_index(op.f('ix_training_webinars_scheduled_start'), 'training_webinars', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_training_webinars_title'), 'training_webinars', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_webinars_title'), table_name='training_webinars')
    op.drop_index(op.f('ix_training_webinars_scheduled_start'), table_name='training_webinars')
    op.drop_index(op.f('ix_training_webinars_provider_id'), table_name='training_webinars')
    op.drop_index(op.f('ix_training_webinars_country_code'), table_name='training_webinars')
    op.drop_table('training_webinars')
    op.drop_index(op.f('ix_training_courses_title'), table_name='training_courses')
    op.drop_index(op.f('ix_training_courses_subdivision_code'), table_name='training_courses')
    op.drop_index(op.f('ix_training_courses_provider_id'), table_name='training_courses')
    op.drop_index(op.f('ix_training_courses_delivery_mode'), table_name='training_courses')
    op.drop_index(op.f('ix_training_courses_country_code'), table_name='training_courses')
    op.drop_table('training_courses')
    op.drop_index(op.f('ix_training_providers_name'), table_name='training_providers')
    op.drop_index(op.f('ix_training_providers_country_code'), table_name='training_providers')
    op.drop_table('training_providers')
    # ### end Alembic commands ###
