"""add facilities specialists and branches

Revision ID: 76a06315c80e
Revises: f0719df7c8f8
Create Date: 2026-10-08 12:09:56.949526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a06315c80e'
down_revision: Union[str, Sequence[str], None] = 'f0719df7c8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('subdivision_code', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('verification_tier', sa.Enum('unverified', 'basic', 'verified', 'featured', name='verification_tier', native_enum=False, length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_country_code'), 'facilities', ['country_code'], unique=False)
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=False)
    op.create_index(op.f('ix_facilities_subdivision_code'), 'facilities', ['subdivision_code'], unique=False)
    op.create_table('specialists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('subdivision_code', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialists_country_code'), 'specialists', ['country_code'], unique=False)
    op.create_index(op.f('ix_specialists_name'), 'specialists', ['name'], unique=False)
    op.create_index(op.f('ix_specialists_slug'), 'specialists', ['slug'], unique=True)
    op.create_index(op.f('ix_specialists_subdivision_code'), 'specialists', ['subdivision_code'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('subdivision_code', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_facility_id'), 'branches', ['facility_id'], unique=False)
    op.create_index(op.f('ix_branches_subdivision_code'), 'branches', ['subdivision_code'], unique=False)
    op.create_table('specialist_specialties',
    sa.Column('specialist_id', sa.String(length=36), nullable=False),
    sa.Column('specialty_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('specialist_id', 'specialty_id')
    )
    op.create_table('dentist_branches',
    sa.Column('specialist_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('specialist_id', 'branch_id')
    )
    op.create_table('opening_hours',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('opens', sa.Time(), nullable=True),
    sa.Column('closes', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'weekday', name='uq_opening_hours_day')
    )
    op.create_index(op.f('ix_opening_hours_branch_id'), 'opening_hours', ['branch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opening_hours_branch_id'), table_name='opening_hours')
    op.drop_table('opening_hours')
    op.drop_table('dentist_branches')
    op.drop_table('specialist_specialties')
    op.drop_index(op.f('ix_branches_subdivision_code'), table_name='branches')
    op.drop_index(op.f('ix_branches_facility_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_specialists_subdivision_code'), table_name='specialists')
    op.drop_index(op.f('ix_specialists_slug'), table_name='specialists')
    op.drop_index(op.f('ix_specialists_name'), table_name='specialists')
    op.drop_index(op.f('ix_specialists_country_code'), table_name='specialists')
    op.drop_table('specialists')
    op.drop_index(op.f('ix_facilities_subdivision_code'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_country_code'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
