"""add jobs board tables

Revision ID: c326aa6733b5
Revises: c7225a91b61f
Create Date: 2026-10-08 16:04:09.750517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c326aa6733b5'
down_revision: Union[str, Sequence[str], None] = 'c7225a91b61f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=2), server_default=sa.text("'KE'"), nullable=False),
    sa.Column('subdivision_code', sa.String(length=30), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=False),
    sa.Column('seniority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'published'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('posted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_branch_id'), 'job_postings', ['branch_id'], unique=False)
    op.create_index(op.f('ix_job_postings_country_code'), 'job_postings', ['country_code'], unique=False)
    op.create_index(op.f('ix_job_postings_employment_type'), 'job_postings', ['employment_type'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_at'), 'job_postings', ['posted_at'], unique=False)
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_index(op.f('ix_job_postings_subdivision_code'), 'job_postings', ['subdivision_code'], unique=False)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    op.create_table('job_postings_specialties',
    sa.Column('posting_id', sa.String(length=36), nullable=False),
    sa.Column('specialty_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('posting_id', 'specialty_id')
    )
    op.create_table('job_salary_ranges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('posting_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_salary_ranges_posting_id'), 'job_salary_ranges', ['posting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_salary_ranges_posting_id'), table_name='job_salary_ranges')
    op.drop_table('job_salary_ranges')
    op.drop_table('job_postings_specialties')
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_subdivision_code'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_at'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_employment_type'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_country_code'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_branch_id'), table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
