"""create_country_reference_tables

Revision ID: f0719df7c8f8
Revises: b3f2a91c47de
Create Date: 2026-09-29 09:26:38.748677

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0719df7c8f8'
down_revision: Union[str, Sequence[str], None] = 'b3f2a91c47de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand_suffix', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('currency_symbol', sa.String(length=8), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('domain', sa.String(length=120), nullable=False),
    sa.Column('phone_prefix', sa.String(length=8), nullable=False),
    sa.Column('subdivision_label', sa.String(length=30), nullable=False),
    sa.Column('subdivision_label_plural', sa.String(length=40), nullable=False),
    sa.Column('city_label', sa.String(length=30), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('specialties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialties_code'), 'specialties', ['code'], unique=True)
    op.create_table('country_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('primary_scheme', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'feature', name='uq_country_feature_key')
    )
    op.create_index(op.f('ix_country_features_country_code'), 'country_features', ['country_code'], unique=False)
    op.create_table('insurance_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_national', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'name', name='uq_insurance_provider_name')
    )
    op.create_index(op.f('ix_insurance_providers_country_code'), 'insurance_providers', ['country_code'], unique=False)
    op.create_table('subdivisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'code', name='uq_subdivision_country_code')
    )
    op.create_index(op.f('ix_subdivisions_country_code'), 'subdivisions', ['country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subdivisions_country_code'), table_name='subdivisions')
    op.drop_table('subdivisions')
    op.drop_index(op.f('ix_insurance_providers_country_code'), table_name='insurance_providers')
    op.drop_table('insurance_providers')
    op.drop_index(op.f('ix_country_features_country_code'), table_name='country_features')
    op.drop_table('country_features')
    op.drop_index(op.f('ix_specialties_code'), table_name='specialties')
    op.drop_table('specialties')
    op.drop_table('countries')
    # ### end Alembic commands ###
